default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: dev
  password: dev
  host: localhost
  port: 5432

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test

production:
  <<: *default
  database: prod
  # You can also set the database URL from an environment variable if needed:
  # url: <%= ENV['DATABASE_URL'] %>
